# cmake/FindCrypto.cmake - Minimal version
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    if(MINGW OR CMAKE_CROSSCOMPILING)
        set(Crypto_FOUND TRUE)
        set(CRYPTO_INCLUDE_DIRS "")
        set(CRYPTO_LIBRARIES advapi32 crypt32)
        message(STATUS "Using MinGW - Found Crypto (advapi32, crypt32)")
    else()
        # MSVC: link trực tiếp Windows libs
        find_library(ADVAPI32_LIB advapi32)
        find_library(CRYPT32_LIB crypt32)

        if(ADVAPI32_LIB AND CRYPT32_LIB)
            set(Crypto_FOUND TRUE)
            set(CRYPTO_INCLUDE_DIRS "")
            set(CRYPTO_LIBRARIES ${ADVAPI32_LIB} ${CRYPT32_LIB})
            message(STATUS "Found Crypto libraries for MSVC")
        else()
            set(Crypto_FOUND FALSE)
            message(FATAL_ERROR "Crypto libraries not found")
        endif()
    endif()
else()
    set(Crypto_FOUND FALSE)
    message(STATUS "Crypto not needed for ${CMAKE_SYSTEM_NAME}")
endif()
